In [1]:
## Cell 6 ##

import pandas as pd
import numpy as np

# import alive
dataset = pd.read_csv("total_cells.csv")
cells = dataset.tail(15)
cells_time = cells['Time (days)'].values
cells_density = 1e6*cells[' Density (1e6/ml)'].values
log_cells_density = np.log(cells_density + 1e-9)

# import dead
death_dataset = pd.read_csv("death_percentage.csv")
death = death_dataset.tail(15)
dead_time = death['Time (days)'].values
dead_density = death[' Dead percentage '].values*cells_density/100
log_dead_density = np.log(dead_density + 1e-9)

In [2]:
cells_density

array([ 232007.13059331,  648951.38829214, 1553876.24915964,
       1970368.94754667, 2371313.17828674, 2691798.97522995,
       2924257.66513507, 3116729.76702572, 2957201.27582355,
       3637653.98088286, 3102138.33553216, 2838623.14848045,
       3199075.31436447, 3575561.20566336, 3480039.56198747])

In [3]:
dead_density

array([  29744.50392222,   58879.21866161,  113399.25289725,
        159339.50068918,  261920.19326244,  297319.01896031,
        328762.69608027,  448759.90728378,  577441.66924365,
        918382.07012427, 1021808.87975122, 1142167.89406314,
       1369229.47380097, 1424582.5710927 , 1482620.40510709])

In [4]:
cells_time

array([ 0,  2,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [5]:
dead_time

array([ 0,  2,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])